#! -*- coding:utf-8 -*-
"""
Convert lines in a .js file from "var" to "let" if the line ended with //let
"""
import os, sys, datetime
def convert_path(src_fd,dst_fd,write_line_number=True):
    for idx,line in enumerate(src_fd.readlines()):
        if write_line_number: sys.stderr.write(str(idx+1)+':')
        striped = line.strip()
        if striped.find('//uncomment ')==0:
            newline = striped[12:]
        elif (len(striped) and striped[:3] == 'var' and striped[-5:] == '//let'):
            newline = line.replace('var','let',1).replace('//let','',1)
        else:
            #continue
            newline = line
        dst_fd.write(newline)
    dst_fd.write('\n/*Auth generated by %s at %s*/\n' % (os.path.basename(sys.argv[0]),datetime.datetime.now()))

def usage():
    print """
Usage:
    $ python %(script_name)s <source js file>
    ex. $ python %(script_name)s sdk.js
    #will output to console with line number

    $ python %(script_name)s <source js file> > <destination js file>
    ex. $ python %(script_name)s sdk.js > sdk_react.js
    #will output to sdk_react.js without line number

    $ python %(script_name)s <source js file> <destination js file>
    ex. $ python %(script_name)s sdk.js sdk_react.js
    #will output to sdk_react.js without line number
""" % {'script_name':sys.argv[0]}

def main():

    pwd = os.path.abspath(os.path.dirname(__file__))

    src_fd = None
    dst_fd = None
    write_line_number = True

    if len(sys.argv)==1:
        src_file = 'sdk.js'
        dst_file = 'sdk_react.js'
        write_line_number = False

    elif ('-h' in sys.argv or '--help' in sys.argv):
        return usage()

    elif len(sys.argv)==2:
        src_file = sys.argv[1]
        dst_file = None

    elif len(sys.argv)==3:
        src_file = sys.argv[1]
        dst_file = sys.argv[2]
        write_line_number = False

    else:
        return usage()
    
    try:
        src = os.path.join(pwd,src_file)
        src_fd = open(src)
        sys.stderr.write('convert %s\n' % src)
        if dst_file:
            dst = os.path.join(pwd,dst_file)
            sys.stderr.write('save to %s\n' % dst)
            dst_fd = open(dst,'w')
        else:
            dst_fd = sys.stdout

        convert_path(src_fd,dst_fd,write_line_number)

        src_fd.close()
        if dst_file:
            dst_fd.close()
    except:
        import traceback
        traceback.print_exc()
        usage()
if __name__ == '__main__':
    main()